# Generated by Django 4.2.13 on 2024-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_recommendation_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rating',
            field=models.FloatField(),
        ),
    ]
